import sqlite3
# from flask import Flask

# app = Flask(__name__)


def QueryDatabase(path):
    """
    Function to query the database and return adjacency matrix of graph
    """
    # TODO This function will not generalise well, Add queries to find largest
    # room number and use that instead of magic numbers
    # TODO also if room number >= 10, char.isnumeric() won't pick it up. Use regexs?
    matrix = []
    db = sqlite3.connect(path)
    cursor = db.execute("SELECT roomID, adjacent FROM rooms;")
    i = 0
    for row in cursor:
        matrix.append(["-" for i in range(5)])  # TODO remove this magic number
        for char in row[1]:
            if char.isnumeric():
                matrix[i][int(char) - 1] = 1
        i += 1
    db.close()
    return matrix


def search(start, end):
    """
    Function runs Dijkstra's algorithm on the distance matrix generated by
    Database query 
    """
    # TODO Add code to get the path rather than the list of distances
    graph = QueryDatabase("project/api/toy.db")
    visited = set()
    distances = [float("inf") for i in graph]
    distances[start] = 0
    current = start
    prev = [None for i in graph]
    while end not in visited:
        visited.add(current)
        for v, node in enumerate(graph[current]):
            if node != "-":
                new_dist = distances[current] + node
                if new_dist < distances[v]:
                    distances[v] = new_dist
        current = distances.index(
            min(filter(lambda x: x not in visited, distances)))

    return distances
# @app.route("/")


def helloworld():
    return "<h1>Hello, World!</h1>"


if __name__ == "__main__":
    print(search(0, 4))
